name: geotypes
description: A lightweight library for GeoJSON data types available dart and flutter.
version: 0.0.2
repository: https://github.com/dartclub/geotypes
homepage: https://geometrico.dev

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0